
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package sistema.votacao.eletronica;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.13
 * 2020-12-25T12:15:21.425Z
 * Generated source version: 2.6.13
 * 
 */

@javax.jws.WebService(
                      serviceName = "VotacaoEletronicaWSService",
                      portName = "VotacaoEletronicaWSPort",
                      targetNamespace = "http://eletronica.votacao.sistema/",
                      wsdlLocation = "http://localhost:8080/VotacaoEletronicaSOAP/services/VotacaoEletronicaWSPort?wsdl",
                      endpointInterface = "sistema.votacao.eletronica.VotacaoEletronicaWS")
                      
public class VotacaoEletronicaWSImpl implements VotacaoEletronicaWS {

    private static final Logger LOG = Logger.getLogger(VotacaoEletronicaWSImpl.class.getName());

    /* (non-Javadoc)
     * @see sistema.votacao.eletronica.VotacaoEletronicaWS#inicioDaVotacao(*
     */
    public java.lang.String inicioDaVotacao() throws Exception_Exception    { 
        LOG.info("Executing operation inicioDaVotacao");
        try {
            java.lang.String _return = "_return-782587375";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see sistema.votacao.eletronica.VotacaoEletronicaWS#tempoRestanteSessao(*
     */
    public java.lang.String tempoRestanteSessao() throws Exception_Exception    { 
        LOG.info("Executing operation tempoRestanteSessao");
        try {
            java.lang.String _return = "_return-1567489320";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see sistema.votacao.eletronica.VotacaoEletronicaWS#duracaoDataSessao(*
     */
    public java.lang.String duracaoDataSessao() throws Exception_Exception    { 
        LOG.info("Executing operation duracaoDataSessao");
        try {
            java.lang.String _return = "_return-1558522289";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see sistema.votacao.eletronica.VotacaoEletronicaWS#listaItemsVotacao(*
     */
    public java.lang.String listaItemsVotacao() throws Exception_Exception    { 
        LOG.info("Executing operation listaItemsVotacao");
        try {
            java.lang.String _return = "_return-333141460";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see sistema.votacao.eletronica.VotacaoEletronicaWS#listaUtilizadoresRegistados(*
     */
    public java.lang.String listaUtilizadoresRegistados() throws Exception_Exception    { 
        LOG.info("Executing operation listaUtilizadoresRegistados");
        try {
            java.lang.String _return = "_return163176586";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see sistema.votacao.eletronica.VotacaoEletronicaWS#listaUtilizadoresSessao(*
     */
    public java.lang.String listaUtilizadoresSessao() throws Exception_Exception    { 
        LOG.info("Executing operation listaUtilizadoresSessao");
        try {
            java.lang.String _return = "_return298331702";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see sistema.votacao.eletronica.VotacaoEletronicaWS#validaUtilizador(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public java.lang.String validaUtilizador(java.lang.String arg0,java.lang.String arg1) throws Exception_Exception    { 
        LOG.info("Executing operation validaUtilizador");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return-2066740369";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see sistema.votacao.eletronica.VotacaoEletronicaWS#removerUtilizador(java.lang.String  arg0 )*
     */
    public java.lang.String removerUtilizador(java.lang.String arg0) throws Exception_Exception    { 
        LOG.info("Executing operation removerUtilizador");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-99159583";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see sistema.votacao.eletronica.VotacaoEletronicaWS#itemGanhador(*
     */
    public java.lang.String itemGanhador() throws Exception_Exception    { 
        LOG.info("Executing operation itemGanhador");
        try {
            java.lang.String _return = "_return437920374";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see sistema.votacao.eletronica.VotacaoEletronicaWS#numeroTotalVotos(*
     */
    public java.lang.String numeroTotalVotos() throws Exception_Exception    { 
        LOG.info("Executing operation numeroTotalVotos");
        try {
            java.lang.String _return = "_return935433239";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see sistema.votacao.eletronica.VotacaoEletronicaWS#votarNoItemSelecionado(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public java.lang.String votarNoItemSelecionado(java.lang.String arg0,java.lang.String arg1) throws Exception_Exception    { 
        LOG.info("Executing operation votarNoItemSelecionado");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return595620032";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see sistema.votacao.eletronica.VotacaoEletronicaWS#associarUtilizador(java.lang.String  arg0 )*
     */
    public java.lang.String associarUtilizador(java.lang.String arg0) throws Exception_Exception    { 
        LOG.info("Executing operation associarUtilizador");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-1766790667";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see sistema.votacao.eletronica.VotacaoEletronicaWS#listarResultadosVotacao(*
     */
    public java.lang.String listarResultadosVotacao() throws Exception_Exception    { 
        LOG.info("Executing operation listarResultadosVotacao");
        try {
            java.lang.String _return = "_return1076020294";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see sistema.votacao.eletronica.VotacaoEletronicaWS#obtemDescricaoItemVotado(java.lang.String  arg0 )*
     */
    public java.lang.String obtemDescricaoItemVotado(java.lang.String arg0) throws Exception_Exception    { 
        LOG.info("Executing operation obtemDescricaoItemVotado");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return945251262";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

}
