
package votacao.eletronica;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.13
 * 2021-01-16T00:47:00.814Z
 * Generated source version: 2.6.13
 */

@WebFault(name = "Exception", targetNamespace = "http://eletronica.votacao/")
public class Exception_Exception extends java.lang.Exception {
    
    private votacao.eletronica.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, votacao.eletronica.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, votacao.eletronica.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public votacao.eletronica.Exception getFaultInfo() {
        return this.exception;
    }
}
