package votacao.eletronica;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.13
 * 2020-12-25T18:09:59.650Z
 * Generated source version: 2.6.13
 * 
 */
@WebServiceClient(name = "VotacaoSoapWSService", 
                  wsdlLocation = "http://localhost:8080/VotacaoSOAP/services/VotacaoSoapWSPort?wsdl",
                  targetNamespace = "http://eletronica.votacao/") 
public class VotacaoSoapWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://eletronica.votacao/", "VotacaoSoapWSService");
    public final static QName VotacaoSoapWSPort = new QName("http://eletronica.votacao/", "VotacaoSoapWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/VotacaoSOAP/services/VotacaoSoapWSPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(VotacaoSoapWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/VotacaoSOAP/services/VotacaoSoapWSPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public VotacaoSoapWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VotacaoSoapWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VotacaoSoapWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public VotacaoSoapWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public VotacaoSoapWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public VotacaoSoapWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns VotacaoSoapWS
     */
    @WebEndpoint(name = "VotacaoSoapWSPort")
    public VotacaoSoapWS getVotacaoSoapWSPort() {
        return super.getPort(VotacaoSoapWSPort, VotacaoSoapWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VotacaoSoapWS
     */
    @WebEndpoint(name = "VotacaoSoapWSPort")
    public VotacaoSoapWS getVotacaoSoapWSPort(WebServiceFeature... features) {
        return super.getPort(VotacaoSoapWSPort, VotacaoSoapWS.class, features);
    }

}
