
package votacao.eletronica;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.13
 * 2021-01-09T00:12:38.460Z
 * Generated source version: 2.6.13
 * 
 */
public final class VotacaoSoapWS_VotacaoSoapWSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://eletronica.votacao/", "VotacaoSoapWSService");

    private VotacaoSoapWS_VotacaoSoapWSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = VotacaoSoapWSService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        VotacaoSoapWSService ss = new VotacaoSoapWSService(wsdlURL, SERVICE_NAME);
        VotacaoSoapWS port = ss.getVotacaoSoapWSPort();  
        
        {
        System.out.println("Invoking numeroTotalVotos...");
        try {
            java.lang.String _numeroTotalVotos__return = port.numeroTotalVotos();
            System.out.println("numeroTotalVotos.result=" + _numeroTotalVotos__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking itemGanhador...");
        try {
            java.lang.String _itemGanhador__return = port.itemGanhador();
            System.out.println("itemGanhador.result=" + _itemGanhador__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking removerUtilizador...");
        java.lang.String _removerUtilizador_arg0 = "_removerUtilizador_arg01286881958";
        try {
            java.lang.String _removerUtilizador__return = port.removerUtilizador(_removerUtilizador_arg0);
            System.out.println("removerUtilizador.result=" + _removerUtilizador__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking votarNoItemSelecionado...");
        java.lang.String _votarNoItemSelecionado_arg0 = "_votarNoItemSelecionado_arg0-299611169";
        java.lang.String _votarNoItemSelecionado_arg1 = "_votarNoItemSelecionado_arg1550601342";
        try {
            java.lang.String _votarNoItemSelecionado__return = port.votarNoItemSelecionado(_votarNoItemSelecionado_arg0, _votarNoItemSelecionado_arg1);
            System.out.println("votarNoItemSelecionado.result=" + _votarNoItemSelecionado__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking teste...");
        port.teste();


        }
        {
        System.out.println("Invoking associarUtilizador...");
        java.lang.String _associarUtilizador_arg0 = "_associarUtilizador_arg0-1693812819";
        try {
            java.lang.String _associarUtilizador__return = port.associarUtilizador(_associarUtilizador_arg0);
            System.out.println("associarUtilizador.result=" + _associarUtilizador__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking listarResultadosVotacao...");
        try {
            java.lang.String _listarResultadosVotacao__return = port.listarResultadosVotacao();
            System.out.println("listarResultadosVotacao.result=" + _listarResultadosVotacao__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking obtemDescricaoItemVotado...");
        java.lang.String _obtemDescricaoItemVotado_arg0 = "_obtemDescricaoItemVotado_arg01805868405";
        try {
            java.lang.String _obtemDescricaoItemVotado__return = port.obtemDescricaoItemVotado(_obtemDescricaoItemVotado_arg0);
            System.out.println("obtemDescricaoItemVotado.result=" + _obtemDescricaoItemVotado__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking tempoRestanteSessao...");
        try {
            java.lang.String _tempoRestanteSessao__return = port.tempoRestanteSessao();
            System.out.println("tempoRestanteSessao.result=" + _tempoRestanteSessao__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking inicioDaVotacao...");
        try {
            java.lang.String _inicioDaVotacao__return = port.inicioDaVotacao();
            System.out.println("inicioDaVotacao.result=" + _inicioDaVotacao__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking listaItemsVotacao...");
        try {
            java.lang.String _listaItemsVotacao__return = port.listaItemsVotacao();
            System.out.println("listaItemsVotacao.result=" + _listaItemsVotacao__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking duracaoDataSessao...");
        try {
            java.lang.String _duracaoDataSessao__return = port.duracaoDataSessao();
            System.out.println("duracaoDataSessao.result=" + _duracaoDataSessao__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking validaUtilizador...");
        java.lang.String _validaUtilizador_arg0 = "_validaUtilizador_arg01038588553";
        java.lang.String _validaUtilizador_arg1 = "_validaUtilizador_arg1-116326126";
        try {
            java.lang.String _validaUtilizador__return = port.validaUtilizador(_validaUtilizador_arg0, _validaUtilizador_arg1);
            System.out.println("validaUtilizador.result=" + _validaUtilizador__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking listaUtilizadoresRegistados...");
        try {
            java.lang.String _listaUtilizadoresRegistados__return = port.listaUtilizadoresRegistados();
            System.out.println("listaUtilizadoresRegistados.result=" + _listaUtilizadoresRegistados__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking listaUtilizadoresSessao...");
        try {
            java.lang.String _listaUtilizadoresSessao__return = port.listaUtilizadoresSessao();
            System.out.println("listaUtilizadoresSessao.result=" + _listaUtilizadoresSessao__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
