package votacao.eletronica;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.13
 * 2020-12-25T18:09:59.639Z
 * Generated source version: 2.6.13
 * 
 */
@WebService(targetNamespace = "http://eletronica.votacao/", name = "VotacaoSoapWS")
@XmlSeeAlso({ObjectFactory.class})
public interface VotacaoSoapWS {

    @WebMethod
    @RequestWrapper(localName = "numeroTotalVotos", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.NumeroTotalVotos")
    @ResponseWrapper(localName = "numeroTotalVotosResponse", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.NumeroTotalVotosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String numeroTotalVotos() throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "itemGanhador", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.ItemGanhador")
    @ResponseWrapper(localName = "itemGanhadorResponse", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.ItemGanhadorResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String itemGanhador() throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "removerUtilizador", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.RemoverUtilizador")
    @ResponseWrapper(localName = "removerUtilizadorResponse", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.RemoverUtilizadorResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String removerUtilizador(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "votarNoItemSelecionado", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.VotarNoItemSelecionado")
    @ResponseWrapper(localName = "votarNoItemSelecionadoResponse", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.VotarNoItemSelecionadoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String votarNoItemSelecionado(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "teste", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.Teste")
    @ResponseWrapper(localName = "testeResponse", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.TesteResponse")
    public void teste();

    @WebMethod
    @RequestWrapper(localName = "associarUtilizador", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.AssociarUtilizador")
    @ResponseWrapper(localName = "associarUtilizadorResponse", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.AssociarUtilizadorResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String associarUtilizador(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "listarResultadosVotacao", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.ListarResultadosVotacao")
    @ResponseWrapper(localName = "listarResultadosVotacaoResponse", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.ListarResultadosVotacaoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String listarResultadosVotacao() throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "obtemDescricaoItemVotado", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.ObtemDescricaoItemVotado")
    @ResponseWrapper(localName = "obtemDescricaoItemVotadoResponse", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.ObtemDescricaoItemVotadoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String obtemDescricaoItemVotado(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "tempoRestanteSessao", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.TempoRestanteSessao")
    @ResponseWrapper(localName = "tempoRestanteSessaoResponse", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.TempoRestanteSessaoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String tempoRestanteSessao() throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "inicioDaVotacao", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.InicioDaVotacao")
    @ResponseWrapper(localName = "inicioDaVotacaoResponse", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.InicioDaVotacaoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String inicioDaVotacao() throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "listaItemsVotacao", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.ListaItemsVotacao")
    @ResponseWrapper(localName = "listaItemsVotacaoResponse", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.ListaItemsVotacaoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String listaItemsVotacao() throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "duracaoDataSessao", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.DuracaoDataSessao")
    @ResponseWrapper(localName = "duracaoDataSessaoResponse", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.DuracaoDataSessaoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String duracaoDataSessao() throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "validaUtilizador", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.ValidaUtilizador")
    @ResponseWrapper(localName = "validaUtilizadorResponse", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.ValidaUtilizadorResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String validaUtilizador(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "listaUtilizadoresRegistados", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.ListaUtilizadoresRegistados")
    @ResponseWrapper(localName = "listaUtilizadoresRegistadosResponse", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.ListaUtilizadoresRegistadosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String listaUtilizadoresRegistados() throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "listaUtilizadoresSessao", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.ListaUtilizadoresSessao")
    @ResponseWrapper(localName = "listaUtilizadoresSessaoResponse", targetNamespace = "http://eletronica.votacao/", className = "votacao.eletronica.ListaUtilizadoresSessaoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String listaUtilizadoresSessao() throws Exception_Exception;
}
